Do not publish packages

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -39,25 +39,25 @@ quality:
 #   rules:
 #     - if: '$CI_COMMIT_BRANCH || $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME'
 
-publish:
-  stage: deploy
-  image: curlimages/curl:latest
-  extends:
-    - .shared_runners
-  rules:
-    - if: $CI_COMMIT_TAG
-      when: always
-  script:
-    - URL="$CI_SERVER_PROTOCOL://$CI_SERVER_HOST:$CI_SERVER_PORT/api/v4/projects/$REGISTRY_PROJECT_ID/packages/composer?job_token=$REGISTRY_TOKEN"
-    - version=$([[ -z "$CI_COMMIT_TAG" ]] && echo "branch=$CI_COMMIT_REF_NAME" || echo "tag=$CI_COMMIT_TAG")
-    - insecure=$([ "$CI_SERVER_PROTOCOL" = "http" ] && echo "--insecure" || echo "")
-    - response=$(curl -s -w "\n%{http_code}" $insecure --data $version $URL)
-    - code=$(echo "$response" | tail -n 1)
-    - body=$(echo "$response" | head -n 1)
-    # Output state information
-    - if [ $code -eq 201 ]; then
-        echo "Package created - Code $code - $body";
-      else
-        echo "Could not create package - Code $code - $body";
-        exit 1;
-      fi
+# publish:
+#   stage: deploy
+#   image: curlimages/curl:latest
+#   extends:
+#     - .shared_runners
+#   rules:
+#     - if: $CI_COMMIT_TAG
+#       when: always
+#   script:
+#     - URL="$CI_SERVER_PROTOCOL://$CI_SERVER_HOST:$CI_SERVER_PORT/api/v4/projects/$REGISTRY_PROJECT_ID/packages/composer?job_token=$REGISTRY_TOKEN"
+#     - version=$([[ -z "$CI_COMMIT_TAG" ]] && echo "branch=$CI_COMMIT_REF_NAME" || echo "tag=$CI_COMMIT_TAG")
+#     - insecure=$([ "$CI_SERVER_PROTOCOL" = "http" ] && echo "--insecure" || echo "")
+#     - response=$(curl -s -w "\n%{http_code}" $insecure --data $version $URL)
+#     - code=$(echo "$response" | tail -n 1)
+#     - body=$(echo "$response" | head -n 1)
+#     # Output state information
+#     - if [ $code -eq 201 ]; then
+#         echo "Package created - Code $code - $body";
+#       else
+#         echo "Could not create package - Code $code - $body";
+#         exit 1;
+#       fi
